services:
  relatorio:
    build: .
    restart: unless-stopped
    expose:
      - "3000"
    environment:
      - RELATORIO_API_KEY=${RELATORIO_API_KEY}
    networks:
      default: {}
      easypanel:
        aliases:
          - n8n_relatorio-fertilidade-app

networks:
  easypanel:
    external: true
    name: easypanel
